#!/bin/sh

CARDSERVER=/etc/init.d/cardserver
SOFTCAM=/etc/init.d/softcam

if [ -f $CARDSERVER ]; then
	echo "sleep 5 sec..."
	sleep 5
	echo "xmodem --> resrarting cardserver..."
	$CARDSERVER restart
fi
if [ -f $SOFTCAM ] ; then
	echo "sleep 10 sec..."
	sleep 10
	echo "xmodem --> resrarting softcam..."
	$SOFTCAM restart
fi
